### ISSUE TITLE
duplicate names in the list of contributors

### ISSUE THREAD

**Issue by JonathanReeve** [xpmethod/xpmethod.github.io#198]
Sierra appears twice, for instance. This is because of the hack in `_layouts/people.html` that displays links to personal websites with `if tag[0].url`. If a contributor is listed once without a URL, and then again with one, they will be displayed twice. I think the solution to this is to move personal website URLs from the project YAML to something like `data/contributors.yaml`, where it can be used as a lookup table. I'll give this a shot.

**Comment by denten** [comment]
Yes, the other thing to explore would be some fancier liquid logic. See for example:

```
{% assign fruits = "orange apple banana apple orange" %}
{{ fruits | split: ' ' | uniq | join: ' ' }}
```

https://help.shopify.com/themes/liquid/filters/array-filters#uniq
