### ISSUE TITLE
switch to tachyons

### ISSUE THREAD

**Issue by denten** [xpmethod/xpmethod.github.io#203]
Follow the template at https://github.com/denten/denten.github.io. Discuss immutable CSS in meeting. The only compromise was https://github.com/denten/denten.github.io/blob/master/public/global.css where I set some global defaults. Copy that file, but set the font to something different to differentiate from my site.

**Comment by nyutka** [comment]
Hello Dennis, can you please check the pages? I change everything to tachyons. Is there anything that I should fix or change, especially the list items.

**Comment by denten** [comment]
Did you file a pull request? I don't see the changes. We can just integrate everything live. The one thing to watch for is mobile layout (which I did on my site with the not small, ns, attribute). From what I remember it was a bit counter-intuitive, where the default was mobile with some special effects for not small screens.

**Comment by nyutka** [comment]
I have just send you a pull request.

**Comment by nyutka** [comment]
Hey @denten  can you, please check the page?

https://nyutka.github.io/xpmethodd.github.io/

**Comment by denten** [comment]
Looks better! On the project page we lost bold in paragraph descriptions. There is now also an extra indent. I am not able to check other pages, since the navigation links are broken.

**Comment by nyutka** [comment]
Right! It was because of tachyons. I have fixed it and other small issues as well.

**Comment by denten** [comment]
Looks much better now! The footer should be in smaller font to match the original. Also, any way for me to check other pages?

**Comment by nyutka** [comment]
I will set up everything and let you know

**Comment by nyutka** [comment]
@denten  I have fixed the url's, so now you can easily go through the links.

**Comment by nyutka** [comment]
I fixed the footer and just send you a PR

**Comment by denten** [comment]
Don't forget to revert the navigation, it is broken at the moment.

**Comment by nyutka** [comment]
Just send you PR

**Comment by denten** [comment]
Anne, can we get rid of SASS now?

**Comment by denten** [comment]
in Events:

    date and location is listed twice
    photos used to scale into a grid
    truncate date to month year to match impact for updates

**Comment by nyutka** [comment]
@denten  what is the reason you want to get rid of SASS? (for me it's the best way of writing CSS)

**Comment by denten** [comment]
Just to reduce complexity. My hope was to have immutable vanilla tachyons for CSS classes and a small global CSS file that provides default font styles etc. (the way I did it on my site).

**Comment by nyutka** [comment]
Sure, no problem.

**Comment by denten** [comment]
There is still one travis build error remaining (I fixed the others) that has to do with tachyons.css linking. Please check.

**Comment by nyutka** [comment]
Sure

**Comment by denten** [comment]
Fixed a bunch more broken links. Travis build passing now. Let's close this issue---I'll open new ones if I see anything else.
