### ISSUE TITLE
snippets now show "updates" instead of blurb?

### ISSUE THREAD

**Issue by aaronplasek** [xpmethod/xpmethod.github.io#91]
If we put "updates" first and the snippet just takes the first x-words, aren't we getting the updates for the project descriptions?

**Comment by JonathanReeve** [comment]
Good point. This seems to be a point for putting the updates at the bottom of the project pages.

**Comment by denten** [comment]
Yes, great point. Looks fine within reason, for example:

http://xpmethod.plaintext.in/strains/public-discourse.html

I'll see if I can write something in liquid to skip the updates page when parsing. Another idea would be to rely on yaml for snipped view (we already implement that, I believe---have to take a look at it). For now, if your updates are not too long, I would still place them on top.
